app:
  host: "0.0.0.0"
  port: 8000

mongodb:
  uri: "mongodb://localhost:27017"
  database: "bank_db"
  users_collection: "users"

logging:
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  level: "INFO"
